name = "ryan-prendergast"
main = "src/worker.ts"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat", "no_nodejs_compat_v2"]

# D1 database for guestbook entries
[[d1_databases]]
binding = "GUESTBOOK_DB"
database_name = "guestbook_entries"
database_id = "c8d26c5f-6c73-4886-87c7-2cc78afef0b0"


[assets]
directory = "public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[build]
command = "npm run build"

[observability.logs]
enabled = true

[env.production]
name = "ryan-prendergast"

[env.staging]
name = "ryan-prendergast-staging"