export type ThemeCategory = "supplied";

export type ThemeStatus = "planned" | "referenced" | "built" | "blocked";

export interface SiteTheme {
  slug: string;
  name: string;
  category: ThemeCategory;
  description: string;
  tags: string[];
  status: ThemeStatus;
  depth: "layout";
  targetUrl: string;
  vibe: string;
  stylesheet: string;
  referencePath: string;
  screenshots: { desktop?: string; mobile?: string };
}

const builtThemeSlugs = new Set([
  "spartan-essay-table",
  "monospace-manual",
  "plaintext-scoreboard",
  "fashion-archive-index",
  "playful-climber-scrapbook",
  "coordinates-art-index",
  "no-css-club",
  "annotated-research-sidenotes",
  "spaced-wordmark-studio",
  "intimate-builder-notes",
  "research-tools-studio",
  "contemporary-art-library",
  "idealist-studio-index",
  "lifeworks-cargo-cv",
  "artist-news-ledger",
  "latent-garden-notebook",
  "fragment-library-journal",
  "ucoz-folk-archive",
  "empty-uncertainty-schema",
  "transparent-news-briefing",
  "graphic-bookmaker-card",
  "experimental-publication-loop",
  "taste-directory",
  "recent-writer-ledger",
  "artist-menu-works",
  "friendly-nerd-hub",
  "playful-games-cabinet",
  "creativity-portal-gallery",
  "design-archive-repository",
  "weblog-topic-facets",
  "research-lab-index",
  "visual-culture-practice",
  "room-wall-portfolio",
  "artist-book-microsite",
  "cyberfeminist-download-index",
  "nonfiction-visual-index",
  "personal-html-bulletin",
  "daily-consumption-digest",
  "data-graphics-portfolio",
  "internet-map-diagram",
  "vernacular-web-essay",
  "cheap-web-manifesto",
  "poetic-computation-article",
  "feral-web-essay",
  "performance-club-index",
  "recurse-link-joy",
  "scenario-forecast-report",
  "rationalist-forum-frontpage",
  "blogroll-essay-archive",
  "now-page-directory",
  "conversational-minimalist",
  "founder-link-index",
  "ai-grant-application-page",
]);

const suppliedThemes: Array<Omit<SiteTheme, "category" | "tags" | "status" | "depth" | "stylesheet" | "referencePath" | "screenshots">> = [
  {
    slug: "spaced-wordmark-studio",
    name: "Spaced Wordmark Studio",
    targetUrl: "https://jarcos.work/",
    vibe: "Spaced Wordmark Studio",
    description: "JARCOS: sparse studio header, large spaced-out wordmark typography, tight work/grid navigation, minimal inquiry link, portfolio entries treated as brand/digital projects.",
  },
  {
    slug: "intimate-builder-notes",
    name: "Intimate Builder Notes",
    targetUrl: "https://www.jia.build/",
    vibe: "Intimate Builder Notes",
    description: "Jia: direct first-person homepage, small nav for about/friends/writing, low-ceremony personal text, visible age/background/work notes, writing links as plain personal artifacts.",
  },
  {
    slug: "monospace-manual",
    name: "Monospace Manual",
    targetUrl: "https://owickstrom.github.io/the-monospace-web/",
    vibe: "Monospace Manual",
    description: "The Monospace Web: single-column monospaced manual, metadata table at top, contents list, sectioned docs, ASCII drawings, tables/forms styled as text UI.",
  },
  {
    slug: "research-tools-studio",
    name: "Research Tools Studio",
    targetUrl: "https://those.tools/",
    vibe: "Research Tools Studio",
    description: "those.tools: tiny studio mark, editorial/software practice copy, sparse contact/social links, project descriptions for arts/social-science software, restrained typographic rhythm.",
  },
  {
    slug: "contemporary-art-library",
    name: "Contemporary Art Library",
    targetUrl: "https://www.midwayart.org/library/",
    vibe: "Contemporary Art Library",
    description: "Midway library: institutional art nav, library/catalog framing, title/name rows, opening-hours utility, archive/library page density.",
  },
  {
    slug: "plaintext-scoreboard",
    name: "Plaintext Scoreboard",
    targetUrl: "https://plaintextsports.com/",
    vibe: "Plaintext Scoreboard",
    description: "Plain Text Sports: timestamped page state, dark/light toggle, date pager, league filters, dense text tables for entries and archives.",
  },
  {
    slug: "fashion-archive-index",
    name: "Fashion Archive Index",
    targetUrl: "https://www.032carchive.com/",
    vibe: "Fashion Archive Index",
    description: "032c archive: huge archive premise, all/authors/photographers/stylists/talent filters, alphabetized names with counts, archive-first rather than blog-first navigation.",
  },
  {
    slug: "idealist-studio-index",
    name: "Idealist Studio Index",
    targetUrl: "https://www.workbyland.com/",
    vibe: "Idealist Studio Index",
    description: "LAND: studio manifesto header, index/studies/information/object tabs, project filtering by discipline, large calm editorial project grid.",
  },
  {
    slug: "playful-climber-scrapbook",
    name: "Playful Climber Scrapbook",
    targetUrl: "https://ashimashiraishi.com/",
    vibe: "Playful Climber Scrapbook",
    description: "Ashima Shiraishi: cheerful emoji-heavy intro, personal contact line, loose list of climbs/projects, art/craft/climbing mix, handmade personal energy.",
  },
  {
    slug: "lifeworks-cargo-cv",
    name: "Lifeworks Cargo CV",
    targetUrl: "https://tamikaabakawood.com/",
    vibe: "Lifeworks Cargo CV",
    description: "Tamika Abaka-Wood: Cargo-like sidebar/title, numbered lifework roles, CV/profile as a dense life-practice list, minimal chrome.",
  },
  {
    slug: "artist-news-ledger",
    name: "Artist News Ledger",
    targetUrl: "https://tegabrain.com/",
    vibe: "Artist News Ledger",
    description: "Tega Brain: latest-news strip, artist name nav, about/news/work sections, exhibition/project announcements as compact dated ledger entries.",
  },
  {
    slug: "latent-garden-notebook",
    name: "Latent Garden Notebook",
    targetUrl: "https://www.nomad.garden/",
    vibe: "Latent Garden Notebook",
    description: "Nomad Garden: personal garden intro, casual image/caption lead, AI/semiotics research notes, loose posts arranged like a cultivated personal notebook.",
  },
  {
    slug: "fragment-library-journal",
    name: "Fragment Library Journal",
    targetUrl: "https://winnielim.org/",
    vibe: "Fragment Library Journal",
    description: "Winnie Lim: menu for about/playlists/journal/notes/library/poetry/archive, latest posts and notes, fragments expressed as a whole, soft literary index.",
  },
  {
    slug: "spartan-essay-table",
    name: "Spartan Essay Table",
    targetUrl: "https://paulgraham.com/",
    vibe: "Spartan Essay Table",
    description: "Paul Graham: almost bare HTML, small centered page, simple top \"New\" links, essay list with minimal typography, no modern cards.",
  },
  {
    slug: "coordinates-art-index",
    name: "Coordinates Art Index",
    targetUrl: "https://jonrafman.com/",
    vibe: "Coordinates Art Index",
    description: "Jon Rafman: lat/lng header, artist title, year-grouped selected works, cryptic symbols, gallery-representation note, dense artwork chronology.",
  },
  {
    slug: "ucoz-folk-archive",
    name: "Ucoz Folk Archive",
    targetUrl: "https://mopppoppp.moy.su/load/rybalka/o_rybalka/ehduard_uspenskij_k_cheloveku_boris_mikhajlov/3-1-0-32",
    vibe: "Ucoz Folk Archive",
    description: "uCoz/Russian file catalog: old portal chrome, registration/catalog links, nested category breadcrumbs, small text modules, file-entry page structure.",
  },
  {
    slug: "empty-uncertainty-schema",
    name: "Empty Uncertainty Schema",
    targetUrl: "https://schemasofuncertainty.com/",
    vibe: "Empty Uncertainty Schema",
    description: "Schemas of Uncertainty: extreme minimal blankness, title-as-object, page as conceptual pause, content surfaced with large negative space.",
  },
  {
    slug: "transparent-news-briefing",
    name: "Transparent News Briefing",
    targetUrl: "https://www.semafor.com/",
    vibe: "Transparent News Briefing",
    description: "Semafor because it is user-supplied: global nav, briefing sections, headline/dek cards, news-column density, clear topic rails.",
  },
  {
    slug: "graphic-bookmaker-card",
    name: "Graphic Bookmaker Card",
    targetUrl: "https://virginiegauthier.info/",
    vibe: "Graphic Bookmaker Card",
    description: "Virginie Gauthier: compact graphic-designer/book-maker identity card, contact-forward layout, plain personal details, light interactive reload/hello flavor.",
  },
  {
    slug: "experimental-publication-loop",
    name: "Experimental Publication Loop",
    targetUrl: "https://re-coding.technology/",
    vibe: "Experimental Publication Loop",
    description: "re-coding: repeated publication statement, digital/experimental/hybrid framing, unusual input/output media, article modules as experimental publication units.",
  },
  {
    slug: "taste-directory",
    name: "Taste Directory",
    targetUrl: "https://www.pi.fyi/",
    vibe: "Taste Directory",
    description: "PI.FYI: theme toggle, rising/browse nav, categories for music/film/TV/books/etc., recommendation directory made from Ryan's links/posts.",
  },
  {
    slug: "recent-writer-ledger",
    name: "Recent Writer Ledger",
    targetUrl: "https://rmorrislevine.info/",
    vibe: "Recent Writer Ledger",
    description: "R Morris Levine: \"recently...\" heading, short linked activity list, writer bio minimalism, essays/events as chronological notes.",
  },
  {
    slug: "artist-menu-works",
    name: "Artist Menu Works",
    targetUrl: "https://setarehshahbazi.com/",
    vibe: "Artist Menu Works",
    description: "Setareh Shahbazi: simple artist home, menu overlay feel, projects/publications/about/contact sections, works listed as title-forward archive.",
  },
  {
    slug: "friendly-nerd-hub",
    name: "Friendly Nerd Hub",
    targetUrl: "https://visakanv.com/",
    vibe: "Friendly Nerd Hub",
    description: "Visa: emoji-rich personal hub, \"Hi, I'm...\" intro, many self-links, bookshelf/email/mentions/pics/contribute nav, warm maximal personality.",
  },
  {
    slug: "playful-games-cabinet",
    name: "Playful Games Cabinet",
    targetUrl: "https://eieio.games/",
    vibe: "Playful Games Cabinet",
    description: "eieio.games: playful personal game/work cabinet, meta-controls, media/speaking/blog/all-work/about nav, game-like text distortion/interaction.",
  },
  {
    slug: "creativity-portal-gallery",
    name: "Creativity Portal Gallery",
    targetUrl: "https://www.enterportal.xyz/",
    vibe: "Creativity Portal Gallery",
    description: "Enter Portal: gallery/uncovered/curate-together nav, \"garden of human creativity\" landing, portal-like browsing of collected work.",
  },
  {
    slug: "design-archive-repository",
    name: "Design Archive Repository",
    targetUrl: "https://archives.design/",
    vibe: "Design Archive Repository",
    description: "archives.design: digital archive description, availability filters, repository/list browsing, graphic-design archive records.",
  },
  {
    slug: "weblog-topic-facets",
    name: "Weblog With Topic Facets",
    targetUrl: "https://simonwillison.net/",
    vibe: "Weblog With Topic Facets",
    description: "Simon Willison: weblog title, About/Subscribe/TILs/Tools nav, topic tag counts, chronological posts with utility/tool density.",
  },
  {
    slug: "research-lab-index",
    name: "Research Lab Index",
    targetUrl: "https://www.anthropic.com/research",
    vibe: "Research Lab Index",
    description: "Anthropic Research because it is user-supplied: sober research landing, policy/learn/news nav, research-team intro, report/article grid.",
  },
  {
    slug: "visual-culture-practice",
    name: "Visual Culture Practice",
    targetUrl: "https://paradyme.zone/",
    vibe: "Visual Culture Practice",
    description: "PARADYME: practice title, merged-collaborative studio statement, visual-culture framing, archive of practice/projects.",
  },
  {
    slug: "room-wall-portfolio",
    name: "Room Wall Portfolio",
    targetUrl: "https://www.nataliajordanova.com/index.htm",
    vibe: "Room Wall Portfolio",
    description: "Natalia Jordanova: old-school personal artist page, contact/social/CV row, poetic statement, sparse artwork/project text.",
  },
  {
    slug: "artist-book-microsite",
    name: "Artist Book Microsite",
    targetUrl: "https://barbaraforever.everyoceanhughes.com/",
    vibe: "Artist Book Microsite",
    description: "Barbara Forever: book/microsite landing, NEXT navigation, editor/designer credit block, publication-object structure.",
  },
  {
    slug: "cyberfeminist-download-index",
    name: "Cyberfeminist Download Index",
    targetUrl: "https://cyberfeminismindex.com/",
    vibe: "Cyberfeminist Download Index",
    description: "Cyberfeminism Index: entry download logs, index/database framing, dense records, activist archive tone, timestamped data traces.",
  },
  {
    slug: "nonfiction-visual-index",
    name: "Nonfiction Visual Index",
    targetUrl: "https://www.maxkohler.com/",
    vibe: "Nonfiction Visual Index",
    description: "Max Kohler: name + \"Non-Fiction Visual Communication\", project index by year/month, compact client/work rows, utilitarian portfolio list.",
  },
  {
    slug: "personal-html-bulletin",
    name: "Personal HTML Bulletin",
    targetUrl: "https://cynnality.com/index.html",
    vibe: "Personal HTML Bulletin",
    description: "cynnality: simple HTML homepage, \"collecting, making, sharing\", last-update note, personal links, work-in-progress bulletin board.",
  },
  {
    slug: "daily-consumption-digest",
    name: "Daily Consumption Digest",
    targetUrl: "https://consumed.today/",
    vibe: "Daily Consumption Digest",
    description: "consumed.today: daily digest of food/media, date headings, categorized consumed items, lightweight diary/archive structure.",
  },
  {
    slug: "data-graphics-portfolio",
    name: "Data Graphics Portfolio",
    targetUrl: "https://www.ashleycai.com/",
    vibe: "Data Graphics Portfolio",
    description: "Ashley Cai: data/graphics journalist intro, CV/social/collections links, view toggles, project thumbnails/list as reporting portfolio.",
  },
  {
    slug: "internet-map-diagram",
    name: "Internet Map Diagram",
    targetUrl: "https://diagram.website/",
    vibe: "Internet Map Diagram",
    description: "Diagram Website: random mode/labels/info/submit/index/roadmap controls, internet map framing, link nodes and index browsing.",
  },
  {
    slug: "vernacular-web-essay",
    name: "Vernacular Web Essay",
    targetUrl: "https://art.teleportacia.org/observation/vernacular/",
    vibe: "Vernacular Web Essay",
    description: "Olia Lialina essay: old web academic essay, language/version links, long illustrated essay structure, blue-link historical web style.",
  },
  {
    slug: "cheap-web-manifesto",
    name: "Cheap Web Manifesto",
    targetUrl: "https://potato.cheap/",
    vibe: "Cheap Web Manifesto",
    description: "The Cheap Web: decorative text hearts, manifesto definitions, small-web link exploration, playful low-cost web philosophy.",
  },
  {
    slug: "no-css-club",
    name: "No CSS Club",
    targetUrl: "https://nocss.club/",
    vibe: "No CSS Club",
    description: "No CSS Club: browser-default HTML, anti-modern-web manifesto, club/list membership, no styling beyond semantic structure.",
  },
  {
    slug: "poetic-computation-article",
    name: "Poetic Computation Article",
    targetUrl: "https://sfpc.study/blog/cellular-automata",
    vibe: "Poetic Computation Article",
    description: "SFPC blog: school nav, donate/store/newsletter links, article title with experimental-school framing, playful institutional blog layout.",
  },
  {
    slug: "feral-web-essay",
    name: "Feral Web Essay",
    targetUrl: "https://paragraph.com/@austinwadesmith/queer-servers-and-feral-webs",
    vibe: "Feral Web Essay",
    description: "Paragraph article: publication article shell, title-first essay, readable longform, newsletter/platform article affordances.",
  },
  {
    slug: "performance-club-index",
    name: "Performance Club Index",
    targetUrl: "https://250kb.club/",
    vibe: "Performance Club Index",
    description: "250KB Club: club manifesto, lightweight website directory, values statement, member/list table with performance-oriented framing.",
  },
  {
    slug: "recurse-link-joy",
    name: "Recurse Link Joy",
    targetUrl: "https://joy.recurse.com/",
    vibe: "Recurse Link Joy",
    description: "Joy of Computing: daily community link, home/about/subscribe/RC nav, weekday post stream, Atom feed prominence.",
  },
  {
    slug: "scenario-forecast-report",
    name: "Scenario Forecast Report",
    targetUrl: "https://ai-2027.com/",
    vibe: "Scenario Forecast Report",
    description: "AI 2027: report nav, summary/research/forecast sections, author/date block, PDF/listen/watch affordances, long scenario document.",
  },
  {
    slug: "rationalist-forum-frontpage",
    name: "Rationalist Forum Frontpage",
    targetUrl: "https://www.lesswrong.com/",
    vibe: "Rationalist Forum Frontpage",
    description: "LessWrong: forum app shell, quick takes/recent/recommended nav, concepts/library links, dense post feed.",
  },
  {
    slug: "blogroll-essay-archive",
    name: "Blogroll Essay Archive",
    targetUrl: "https://slatestarcodex.com/",
    vibe: "Blogroll Essay Archive",
    description: "Slate Star Codex: WordPress-like blog header, top-post/archive/comment/feed nav, blogroll sidebar sections, chronological essay list.",
  },
  {
    slug: "annotated-research-sidenotes",
    name: "Annotated Research Sidenotes",
    targetUrl: "https://gwern.net/",
    vibe: "Annotated Research Sidenotes",
    description: "Gwern: categorized essay index, warnings/feature notes, sidenotes/link annotations/backlinks feel, dense research typography.",
  },
  {
    slug: "now-page-directory",
    name: "Now Page Directory",
    targetUrl: "https://nownownow.com/about",
    vibe: "Now Page Directory",
    description: "nownownow about: explanatory personal-web copy, now-page concept, directory framing, simple centered text links.",
  },
  {
    slug: "conversational-minimalist",
    name: "Conversational Minimalist",
    targetUrl: "https://sive.rs/",
    vibe: "Conversational Minimalist",
    description: "Derek Sivers: centered personal intro, compact self-description, simple nav links, essay/book/course list with conversational tone.",
  },
  {
    slug: "founder-link-index",
    name: "Founder Link Index",
    targetUrl: "https://patrickcollison.com/",
    vibe: "Founder Link Index",
    description: "Patrick Collison: bare personal nav, concise section links, link index of advice/blog/bookshelf/culture/labs/progress/questions.",
  },
  {
    slug: "ai-grant-application-page",
    name: "AI Grant Application Page",
    targetUrl: "https://aigrant.com/",
    vibe: "AI Grant Application Page",
    description: "AI Grant because it is user-supplied: accelerator landing page, grant amount hero, credits/summit/advisor details, application CTA structure.",
  },
];

export const siteThemes: SiteTheme[] = suppliedThemes.map((theme) => ({
  ...theme,
  category: "supplied",
  tags: ["user supplied", "site mimic"],
  status: builtThemeSlugs.has(theme.slug) ? "built" : "planned",
  depth: "layout",
  stylesheet: `/theme-mimics/${theme.slug}.css`,
  referencePath: `docs/theme-references/sites/${theme.slug}.md`,
  screenshots: {},
}));

export const defaultThemeSlug = "spartan-essay-table";

export function getThemeBySlug(slug: string | null | undefined): SiteTheme {
  return siteThemes.find((theme) => theme.slug === slug) || siteThemes[0];
}

export function getThemesByCategory(): Record<ThemeCategory, SiteTheme[]> {
  return { supplied: siteThemes };
}
